### PR TITLE
release(v1.8.0-alpha.2): prepare release

### PR DESCRIPTION
**Pull request by smira**
This is the official v1.8.0-alpha.2 release.

### CODE REVIEW

**Comment by frezbo** [comment]
we have one more rockchip board not pulled in here, should we do that now?

**Review by frezbo — APPROVED** [review]

**Comment by smira** [comment]
> we have one more rockchip board not pulled in here, should we do that now?

I can add that in.

**Comment by smira** [comment]
> > we have one more rockchip board not pulled in here, should we do that now?
> 
> I can add that in.

Updated in this PR.

**Review by frezbo — APPROVED** [review]

**Pull request merged**
