### PR TITLE
release(v1.7.0): prepare release

### PR DESCRIPTION
**Pull request by smira**
This is the official v1.7.0 release.

Signed-off-by: Andrey Smirnov <andrey.smirnov@siderolabs.com>

### CODE REVIEW

**Review by frezbo — CHANGES_REQUESTED** [review]
Don't we need to cut `v0.1.0` of all these https://github.com/siderolabs/overlays/blob/main/internal/overlays/overlays.yaml#L1?

**Comment by smira** [comment]
> Don't we need to cut `v0.1.0` of all these [`main`/internal/overlays/overlays.yaml#L1](https://github.com/siderolabs/overlays/blob/main/internal/overlays/overlays.yaml?rgh-link-date=2024-04-19T10%3A45%3A17Z#L1)?

do we need to? I don't know if they're tested enough at this moment. I can only say that RPi one works with RPi4. 

I think we can take them out of beta during the 1.7 release cycle

**Comment by smira** [comment]
In other words, 'beta' quality is probably fair at this moment.

**Review by frezbo — APPROVED** [review]

**Comment by frezbo** [comment]
> In other words, 'beta' quality is probably fair at this moment.

Yeh, fair enough

**Pull request merged**
